#include "FreeRTOS.h"
#include "task.h"
#include "queue.h"
#include "semphr.h"

#include "app_types.h"
#include "tasks/sensor_task.h"
#include "tasks/processing_task.h"
#include "tasks/uart_task.h"
#include "tasks/watchdog_task.h"
#include "tasks/cli_task.h"
#include "drivers/bme280.h"
#include "drivers/flash_config.h"

/*
 * NOTE: When CubeMX generates the project, it creates:
 *   - SystemClock_Config()   - configures PLL to 100MHz
 *   - MX_GPIO_Init()         - configures GPIO pins
 *   - MX_I2C1_Init()         - configures I2C1 for BME280
 *   - MX_USART2_Init()       - configures UART2 (ST-Link, 115200 baud)
 *   - MX_IWDG_Init()         - configures IWDG for ~2s timeout
 *
 * Declare those functions extern here when the generated file exists.
 */

/* -------------------------------------------------------------------------
 * Global variables defined here, declared extern in app_types.h
 * ------------------------------------------------------------------------- */
QueueHandle_t     g_sensor_queue;
QueueHandle_t     g_print_queue;
QueueHandle_t     g_rx_char_queue;

system_stats_t    g_stats;
SemaphoreHandle_t g_stats_mutex;

volatile uint32_t g_watchdog_checkin_flags = 0;

/* -------------------------------------------------------------------------
 * Task handles (optional - used for vTaskSuspend in CLI, watermark checks)
 * ------------------------------------------------------------------------- */
static TaskHandle_t h_sensor;
static TaskHandle_t h_processing;
static TaskHandle_t h_uart;
static TaskHandle_t h_watchdog;
static TaskHandle_t h_cli;

/* -------------------------------------------------------------------------
 * FreeRTOS hook implementations (required when hooks are enabled in config)
 * ------------------------------------------------------------------------- */

void vApplicationIdleHook(void)
{
    /* Called by the idle task when no other task is ready.
       Put the CPU into WFI (Wait For Interrupt) sleep.
       The next interrupt (SysTick, UART RX, etc.) wakes it up.
       This reduces power consumption without needing deep sleep modes. */
    /* __WFI(); */   /* TODO: uncomment when CMSIS is present */
}

void vApplicationStackOverflowHook(TaskHandle_t xTask, char *pcTaskName)
{
    /* Called when configCHECK_FOR_STACK_OVERFLOW detects a stack overflow.
       The task name tells you which task overflowed.
       Do not return from this function. */
    (void)xTask;
    (void)pcTaskName;
    /* Disable interrupts and halt. Debugger can inspect pcTaskName. */
    /* __disable_irq(); */
    while (1);
}

void vApplicationMallocFailedHook(void)
{
    /* Called when pvPortMalloc() returns NULL (heap exhausted).
       This should never happen if heap size is configured correctly.
       If it does, increase configTOTAL_HEAP_SIZE or reduce stack sizes. */
    while (1);
}

/* -------------------------------------------------------------------------
 * main
 * ------------------------------------------------------------------------- */
int main(void)
{
    /*
     * HAL and peripheral init (generated by CubeMX).
     * TODO: uncomment when CubeMX project is generated.
     *
     * HAL_Init();
     * SystemClock_Config();
     * MX_GPIO_Init();
     * MX_I2C1_Init();
     * MX_USART2_Init();
     * MX_IWDG_Init();
     */

    /* Zero-initialise stats */
    g_stats = (system_stats_t){0};

    /* Create synchronisation primitives */
    g_stats_mutex    = xSemaphoreCreateMutex();
    g_sensor_queue   = xQueueCreate(4,  sizeof(sensor_reading_t));
    g_print_queue    = xQueueCreate(8,  sizeof(print_msg_t));
    g_rx_char_queue  = xQueueCreate(32, sizeof(uint8_t));

    /* Assert all primitives created successfully.
       If any is NULL, heap is too small for the requested sizes. */
    configASSERT(g_stats_mutex   != NULL);
    configASSERT(g_sensor_queue  != NULL);
    configASSERT(g_print_queue   != NULL);
    configASSERT(g_rx_char_queue != NULL);

    /* Initialise sensor (reads calibration coefficients from BME280 OTP) */
    if (bme280_init() != STATUS_OK) {
        /* Sensor not responding - system will report errors via sensor_task */
    }

    /* Create tasks.
       Stack size is in WORDS (4 bytes each on Cortex-M4).
       512 words = 2048 bytes. */
    xTaskCreate(sensor_task,     "Sensor",  SENSOR_TASK_STACK_WORDS,     NULL, SENSOR_TASK_PRIORITY,     &h_sensor);
    xTaskCreate(processing_task, "Proc",    PROCESSING_TASK_STACK_WORDS, NULL, PROCESSING_TASK_PRIORITY, &h_processing);
    xTaskCreate(uart_task,       "UART",    UART_TASK_STACK_WORDS,       NULL, UART_TASK_PRIORITY,       &h_uart);
    xTaskCreate(watchdog_task,   "WDG",     WATCHDOG_TASK_STACK_WORDS,   NULL, WATCHDOG_TASK_PRIORITY,   &h_watchdog);
    xTaskCreate(cli_task,        "CLI",     CLI_TASK_STACK_WORDS,        NULL, CLI_TASK_PRIORITY,        &h_cli);

    configASSERT(h_sensor     != NULL);
    configASSERT(h_processing != NULL);
    configASSERT(h_uart       != NULL);
    configASSERT(h_watchdog   != NULL);
    configASSERT(h_cli        != NULL);

    /* Start the scheduler. This call does not return.
       Execution continues inside the highest-priority ready task. */
    vTaskStartScheduler();

    /* Should never reach here. If it does, heap was too small to create
       the idle task. Increase configTOTAL_HEAP_SIZE. */
    while (1);
}
